monitor-prometheus:
  image:
    default: 868968213119.dkr.ecr.ap-southeast-1.amazonaws.com/prometheus:main
  replicas: 1

monitor-grafana:
  image:
    default: 868968213119.dkr.ecr.ap-southeast-1.amazonaws.com/grafana:main
  replicas: 1

monitor-loki:
  image:
    default: 868968213119.dkr.ecr.ap-southeast-1.amazonaws.com/loki:main
  replicas: 1

jenkins-master:
  image:
    default: 868968213119.dkr.ecr.ap-southeast-1.amazonaws.com/jenkin-master:main
  replicas: 1

jenkins-worker:
  image:
    default: 868968213119.dkr.ecr.ap-southeast-1.amazonaws.com/jenkin-agent:main
  replicas: 1

chain:
  image:
    default: 868968213119.dkr.ecr.ap-southeast-1.amazonaws.com/gaia:main
    init-node: 868968213119.dkr.ecr.ap-southeast-1.amazonaws.com/chain-init-node:main
  cpu: 512
  memory: 1024
  replicas: 0

bootstrap-chain-validator:
  image:
    default: 868968213119.dkr.ecr.ap-southeast-1.amazonaws.com/gaia:main
  replicas: 0
  network: bridge