main_dns_domain:  dev.shareableasset.com
gcp_login_dns: shareableasset.com
aws_default_region: ap-southeast-1
aws_vpc_name: interopera
aws_bucket_alb_id: "114774131450"
vpc_cidr_prefix: "18.0"
ecr_repositories:
  [
    "jenkin-master",
    "jenkin-agent",
    "prometheus",
    "grafana",
    "loki",
    "fluentbit",
    "ecs-utils",
    "gaia",
  ]
ecs_ami_version: amazon-ecs@v0.0.1
ecs_private_dns: ecs.private
ecs_fluentbit_image: 868968213119.dkr.ecr.ap-southeast-1.amazonaws.com/fluentbit:main
jenkins:
  branch: main
  secret: f59d462615fb0089447ef62ab25b9eb78aa5b57877f6383b093fdbbd50d2afb8
github:
  id: interopera-bot
  token: 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
google_auth:
  client_id: 653780333302-l4osm6m2drmak7vl6r2tbo7vf3t3oafc.apps.googleusercontent.com
  client_secret: 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
grafana:
  admin_password: fXPxURfq4mRXcgv496OmpXjU86vVT5oVJ5w7OSCN7Vk
  google_id: 653780333302-98m7sssok4si9s50jofhlrorm91h0mhh.apps.googleusercontent.com
  google_secret: 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
chain_gaia:
  BOOTSTRAP_IP_PREFIX: "9.9.9"
  VALIDATOR_STATIC_IPS: [
    "18.0.41.50",
    "",
    "",
    ""
  ]
  NUMS_OF_NODE: "6"
  KEYRING_BACKEND: test
  CHAIN_ID: interopera
  MIN_GAS_PRICE: 0uatom